//! Enforces `RBAC_MODEL.md` §5 — "exactly one Master key exists" — **at the database level**,
//! rather than trusting application logic to hold the line.
//!
//! Application guards are necessary but not sufficient here. A second master row is the one piece
//! of state from which every other control can be undone: masters bypass per-hook RBAC, may set
//! `run_as_user`, and administer other keys. Any path that ever writes `is_master = true` — a
//! future handler, a migration, an operator at a `psql` prompt, a restored backup — must be unable
//! to produce a second one, and only the engine can promise that.
//!
//! # Why a generated column instead of a partial index
//!
//! The natural spelling is `CREATE UNIQUE INDEX ... ON api_keys (is_master) WHERE is_master`.
//! PostgreSQL and SQLite both support that; **MySQL does not** — it has no `WHERE` clause on
//! `CREATE INDEX` — and `Cargo.toml` enables the MySQL driver, so a Postgres-only constraint would
//! silently leave MySQL deployments unprotected.
//!
//! The portable equivalent, which §5 anticipates, is a nullable marker column carrying a single
//! non-null value under a *plain* unique index: NULLs do not collide with each other under SQL's
//! unique semantics, so an unlimited number of non-master rows coexist while at most one row can
//! carry the marker.
//!
//! The marker is **generated by the database** from `is_master` rather than maintained by the
//! application. That distinction is the whole point: a hand-maintained marker could be bypassed by
//! writing `is_master = true` and leaving the marker NULL, which is precisely the "application
//! logic alone" §5 rules out. Deriving it makes the constraint unbypassable by any writer.
//!
//! Every supported engine expresses this, with one syntactic split: PostgreSQL's generated columns
//! must be `STORED` (it gained `VIRTUAL` only in 18), while SQLite permits only `VIRTUAL` for a
//! column added through `ALTER TABLE`. MySQL accepts either and is given `VIRTUAL` to avoid the
//! table rewrite. The three statements are otherwise identical and produce identical semantics.
//!
//! # Failure mode on an already-inconsistent database
//!
//! If a deployment somehow already holds two master rows, creating the unique index fails and the
//! migration aborts, taking startup with it. That is deliberate. A database with two masters has
//! no correct interpretation this migration could pick — deciding which one is legitimate is an
//! operator's judgement, not a schema change's — and refusing to start is the honest outcome.
//! Recovery is to demote or delete the extra row directly and restart.

use sea_orm::{ConnectionTrait, DatabaseBackend};
use sea_orm_migration::prelude::*;

#[derive(DeriveMigrationName)]
pub struct Migration;

/// Name of the derived marker column. Deliberately absent from `api_key::Model`: SeaORM builds
/// explicit column lists from the entity, so an undeclared column is invisible to every query and
/// can never appear in an `INSERT` — which is required, since the engine rejects writes to a
/// generated column.
const MARKER_COLUMN: &str = "master_marker";
/// Name of the unique index that does the actual enforcing.
const MARKER_INDEX: &str = "idx_api_keys_master_marker";

impl Migration {
    /// The `ALTER TABLE` that adds the derived marker, in this backend's dialect.
    fn add_marker_column(backend: DatabaseBackend) -> String {
        // `CASE WHEN is_master THEN 1 ELSE NULL END` reads identically on all three engines:
        // PostgreSQL evaluates a native boolean, MySQL and SQLite a truthy integer.
        let expression = "CASE WHEN is_master THEN 1 ELSE NULL END";
        let storage = match backend {
            // PostgreSQL requires STORED; VIRTUAL generated columns arrived only in 18 and the
            // minimum supported version here is 12.
            DatabaseBackend::Postgres => "STORED",
            // SQLite allows *only* VIRTUAL for a generated column added via ALTER TABLE. MySQL
            // accepts both, and VIRTUAL avoids rewriting the table.
            _ => "VIRTUAL",
        };
        format!(
            "ALTER TABLE api_keys ADD COLUMN {MARKER_COLUMN} INTEGER \
             GENERATED ALWAYS AS ({expression}) {storage}"
        )
    }
}

#[async_trait::async_trait]
impl MigrationTrait for Migration {
    async fn up(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        let db = manager.get_connection();
        let backend = db.get_database_backend();

        db.execute_unprepared(&Migration::add_marker_column(backend)).await?;
        db.execute_unprepared(&format!(
            "CREATE UNIQUE INDEX {MARKER_INDEX} ON api_keys ({MARKER_COLUMN})"
        ))
        .await?;

        Ok(())
    }

    async fn down(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        let db = manager.get_connection();

        // Index first: SQLite refuses `DROP COLUMN` on a column that participates in an index, and
        // dropping the index before the column it covers is correct everywhere else too.
        db.execute_unprepared(&format!("DROP INDEX {MARKER_INDEX}")).await?;
        db.execute_unprepared(&format!("ALTER TABLE api_keys DROP COLUMN {MARKER_COLUMN}")).await?;

        Ok(())
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// PostgreSQL is the one backend that cannot take `VIRTUAL`, and SQLite is the one that cannot
    /// take `STORED` on an added column. Getting the pair backwards would fail only against a real
    /// server, which the unit suite never starts — so the dialect choice is pinned here.
    #[test]
    fn each_backend_gets_the_only_storage_class_it_accepts() {
        assert!(
            Migration::add_marker_column(DatabaseBackend::Postgres).ends_with("STORED"),
            "PostgreSQL supports only STORED generated columns before version 18"
        );
        assert!(
            Migration::add_marker_column(DatabaseBackend::Sqlite).ends_with("VIRTUAL"),
            "SQLite supports only VIRTUAL for a generated column added via ALTER TABLE"
        );
        assert!(
            Migration::add_marker_column(DatabaseBackend::MySql).ends_with("VIRTUAL"),
            "MySQL accepts both; VIRTUAL avoids rewriting the table"
        );
    }

    /// The marker must be *derived*, never assignable. A literal default, or any expression not
    /// reading `is_master`, would reintroduce exactly the bypass this migration exists to close:
    /// writing `is_master = true` while leaving the marker NULL.
    #[test]
    fn the_marker_is_derived_from_is_master_on_every_backend() {
        for backend in [DatabaseBackend::Postgres, DatabaseBackend::Sqlite, DatabaseBackend::MySql]
        {
            let ddl = Migration::add_marker_column(backend);
            assert!(
                ddl.contains("GENERATED ALWAYS AS") && ddl.contains("is_master"),
                "{backend:?} marker must be generated from is_master, got: {ddl}"
            );
        }
    }
}
